import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

test("home page supports both status view and hierarchical library view from the same JavaGuide data", async () => {
  const source = await readFile(`${root}/frontend/components/home-page.js`, "utf8");
  const documentRouteSource = await readFile(`${root}/frontend/app/documents/[slug]/page.js`, "utf8");
  const learnSource = await readFile(`${root}/frontend/components/learn-workspace.js`, "utf8");
  const styles = await readFile(`${root}/frontend/app/globals.css`, "utf8");

  assert.match(source, /mode = searchParams\.get\("mode"\) \|\| "status"/);
  assert.match(source, /panel = searchParams\.get\("panel"\)/);
  assert.match(source, /buildLibraryTree/);
  assert.match(source, /flattenLibrarySegments/);
  assert.match(source, /LibraryTreeNode/);
  assert.match(source, /LibraryBrowser/);
  assert.match(source, /LoginModal/);
  assert.match(source, /postJson\("\/api\/auth\/login"/);
  assert.match(source, /FolderAggregateBar/);
  assert.match(source, /includeIgnoredDocuments/);
  assert.match(source, /包含忽略文档/);
  assert.match(source, /ll-ignored-chip/);
  assert.match(source, /ll-library-ignore-button/);
  assert.match(source, /onToggleIgnored/);
  assert.match(source, /按状态看/);
  assert.match(source, /登录 \/ 创建账号/);
  assert.match(source, /isLoggedIn=\{Boolean\(profile\?\.user\?\.id\)\}/);
  assert.match(source, /子文件夹/);
  assert.match(source, /当前层级文档/);
  assert.match(source, /我的资料 \/ /);
  assert.match(source, /getDocumentPreview/);
  assert.match(source, /buildReentryPlan/);
  assert.match(source, /今天先做什么/);
  assert.match(source, /备选动作/);
  assert.match(source, /开始新的一篇/);
  assert.match(source, /今天先不练这个/);
  assert.match(source, /今天先不读这个/);
  assert.match(source, /ll-detail-cta/);
  assert.doesNotMatch(source, /打开阅读页/);
  assert.doesNotMatch(source, /buildDetailHref/);
  assert.doesNotMatch(source, /查看准备页/);
  assert.doesNotMatch(source, /Anthropic: Engineering Context for Claude/);

  assert.match(documentRouteSource, /redirect\(`\/learn/);
  assert.doesNotMatch(documentRouteSource, /DocumentPrepPage/);

  assert.match(learnSource, /TrainingOverviewCard/);
  assert.match(learnSource, /TrainingThreadCard/);
  assert.match(learnSource, /TrainingAssistantRail/);
  assert.match(learnSource, /TrainingCompletionSummaryPage/);
  assert.match(learnSource, /ReadingDocumentContent/);
  assert.match(learnSource, /ReadingSelectionPopover/);
  assert.match(learnSource, /ReadingAssistantBubble/);
  assert.match(learnSource, /ReadingReentryCard/);
  assert.match(learnSource, /继续上次训练/);
  assert.match(learnSource, /buildReadingTrainingBanner/);
  assert.match(learnSource, /Mermaid 图表暂以源码显示/);
  assert.match(learnSource, /visibleReadProgressPercent/);
  assert.match(learnSource, /toggleIgnoredDocument/);
  assert.match(learnSource, /标记为忽略/);
  assert.match(learnSource, /标记为仅阅读完成/);
  assert.doesNotMatch(learnSource, /搁置/);
  assert.doesNotMatch(learnSource, /reader-mastery-pill/);
  assert.doesNotMatch(learnSource, /document-completion-card/);
  assert.match(learnSource, /问任何关于这篇的问题/);
  assert.match(learnSource, /reading-composer-starters/);
  assert.match(learnSource, /normalizeAssistantMarkdown\(entry\.body/);
  assert.doesNotMatch(learnSource, /12 道题/);
  assert.doesNotMatch(learnSource, /readingTrainingBannerLabel/);
  assert.doesNotMatch(learnSource, /readingTrainingBannerClickable/);
  assert.doesNotMatch(learnSource, /reader-progress-track/);
  assert.doesNotMatch(learnSource, /is-read/);
  assert.doesNotMatch(learnSource, /is-unread/);
  assert.doesNotMatch(learnSource, /<p>\{entry\.body\}<\/p>/);
  assert.match(learnSource, /AnimatedMasteryValue/);
  assert.match(learnSource, /buildTrainingCompletionSummary/);
  assert.match(learnSource, /已记住的内容\(系统会基于这些追问\)/);
  assert.match(learnSource, /正在理解你的回答/);
  assert.match(learnSource, /明天还有事/);
  assert.match(learnSource, /立即重练/);
  assert.match(learnSource, /分享内容只展示你的学习成果/);

  assert.match(styles, /\.ll-tree-shell\s*\{/);
  assert.match(styles, /\.ll-folder-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(styles, /\.ll-folder-progress\s*\{/);
  assert.match(styles, /\.ll-include-ignored-toggle\s*\{/);
  assert.match(styles, /\.ll-ignored-chip\s*\{/);
  assert.match(styles, /\.ll-library-ignore-button\s*\{/);
  assert.match(styles, /\.ll-library-document-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(3,\s*minmax\(0,\s*1fr\)\)/);
  assert.match(styles, /\.ll-breadcrumbs\s*\{/);
  assert.doesNotMatch(styles, /\.ll-prep-page\s*\{/);
  assert.doesNotMatch(styles, /\.ll-prep-stage\s*\{/);
  assert.doesNotMatch(styles, /\.ll-prep-popover\s*,\s*\.ll-prep-menu\s*\{/);
  assert.match(styles, /\.ll-training-page\s*\{/);
  assert.match(styles, /\.ll-score-card\s*,/);
  assert.match(styles, /\.ll-training-rail\s*\{/);
  assert.match(styles, /\.ll-training-summary-page\s*\{/);
  assert.match(styles, /\.ll-summary-hero\s*\{/);
  assert.match(styles, /\.ll-summary-score-blocks\s*\{/);
  assert.match(styles, /\.ll-summary-weak-card\s*\{/);
  assert.match(styles, /\.reading-document-surface\s*\{/);
  assert.match(styles, /\.reading-reentry-copy\s*\{/);
  assert.match(styles, /\.reading-code-block\s*\{/);
  assert.match(styles, /\.reading-training-banner\.tone-action\s*,/);
  assert.doesNotMatch(styles, /\.reader-mastery-pill\s*\{/);
  assert.doesNotMatch(styles, /\.document-completion-card\s*\{/);
  assert.doesNotMatch(styles, /\.reader-progress-track\s*\{/);
  assert.doesNotMatch(styles, /\.reading-paragraph\.is-read\s*\{/);
  assert.doesNotMatch(styles, /\.reading-paragraph\.is-unread\s*\{/);
  assert.match(styles, /\.reading-selection-popover\s*\{/);
  assert.match(styles, /\.reading-ai-message\s*\{/);
});
